/* tslint:disable */
/* eslint-disable */
/**
 * Easy Picsy - Photobooth Payment API
 *        A comprehensive API for managing photobooth events, QR code payments, and real-time communication.              ## Features       - 🎫 Event Management (CRUD operations)       - 💳 PayMongo Payment Integration         - 🔄 Dynamic QR Code Generation (30-min expiry)       - ⚡ Real-time WebSocket Updates       - 🔐 Supabase Authentication       - 📊 Payment Analytics              ## Authentication       Most endpoints require a Bearer token from Supabase authentication.       Add your token to the \"Authorize\" button above to test endpoints.              ## WebSocket Real-time Communication              **Connection URL:** `ws://localhost:3000/events`              **Authentication:** Include JWT token in one of these ways:       - `auth.token` in connection options       - `Authorization: Bearer <token>` header       - `token` query parameter              **Available Events:**              ### Client → Server       - `joinEvent` - Join event room for updates         ```json         { \"eventId\": \"uuid\" }         ```       - `leaveEvent` - Leave event room         ```json         { \"eventId\": \"uuid\" }         ```              ### Server → Client       - `qrStatusUpdate` - QR code status changed       - `paymentReceived` - Payment completed       - `qrCodeGenerated` - New QR code created       - `qrExpiryWarning` - QR code expires soon       - `connectionStatus` - Connection status updates              **Room-based Broadcasting:** Events are sent only to clients in specific event rooms.     
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@easypicsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost:3000".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
