/* tslint:disable */
/* eslint-disable */
/**
 * Easy Picsy - Photobooth Payment API
 *        A comprehensive API for managing photobooth events, QR code payments, and real-time communication.              ## Features       - 🎫 Event Management (CRUD operations)       - 💳 PayMongo Payment Integration         - 🔄 Dynamic QR Code Generation (30-min expiry)       - ⚡ Real-time WebSocket Updates       - 🔐 Supabase Authentication       - 📊 Payment Analytics              ## Authentication       Most endpoints require a Bearer token from Supabase authentication.       Add your token to the \"Authorize\" button above to test endpoints.              ## WebSocket Real-time Communication              **Connection URL:** `ws://localhost:3000/events`              **Authentication:** Include JWT token in one of these ways:       - `auth.token` in connection options       - `Authorization: Bearer <token>` header       - `token` query parameter              **Available Events:**              ### Client → Server       - `joinEvent` - Join event room for updates         ```json         { \"eventId\": \"uuid\" }         ```       - `leaveEvent` - Leave event room         ```json         { \"eventId\": \"uuid\" }         ```              ### Server → Client       - `qrStatusUpdate` - QR code status changed       - `paymentReceived` - Payment completed       - `qrCodeGenerated` - New QR code created       - `qrExpiryWarning` - QR code expires soon       - `connectionStatus` - Connection status updates              **Room-based Broadcasting:** Events are sent only to clients in specific event rooms.     
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@easypicsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigurationParameters {
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    username?: string;
    password?: string;
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    basePath?: string;
    serverIndex?: number;
    baseOptions?: any;
    formDataCtor?: new () => any;
}

export class Configuration {
    /**
     * parameter for apiKey security
     * @param name security name
     * @memberof Configuration
     */
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    /**
     * parameter for basic security
     *
     * @type {string}
     * @memberof Configuration
     */
    username?: string;
    /**
     * parameter for basic security
     *
     * @type {string}
     * @memberof Configuration
     */
    password?: string;
    /**
     * parameter for oauth2 security
     * @param name security name
     * @param scopes oauth2 scope
     * @memberof Configuration
     */
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    /**
     * override base path
     *
     * @type {string}
     * @memberof Configuration
     */
    basePath?: string;
    /**
     * override server index
     *
     * @type {number}
     * @memberof Configuration
     */
    serverIndex?: number;
    /**
     * base options for axios calls
     *
     * @type {any}
     * @memberof Configuration
     */
    baseOptions?: any;
    /**
     * The FormData constructor that will be used to create multipart form data
     * requests. You can inject this here so that execution environments that
     * do not support the FormData class can still run the generated client.
     *
     * @type {new () => FormData}
     */
    formDataCtor?: new () => any;

    constructor(param: ConfigurationParameters = {}) {
        this.apiKey = param.apiKey;
        this.username = param.username;
        this.password = param.password;
        this.accessToken = param.accessToken;
        this.basePath = param.basePath;
        this.serverIndex = param.serverIndex;
        this.baseOptions = {
            ...param.baseOptions,
            headers: {
                ...param.baseOptions?.headers,
            },
        };
        this.formDataCtor = param.formDataCtor;
    }

    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    public isJsonMime(mime: string): boolean {
        const jsonMime: RegExp = new RegExp('^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$', 'i');
        return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === 'application/json-patch+json');
    }
}
