/* tslint:disable */
/* eslint-disable */
/**
 * Easy Picsy - Photobooth Payment API
 *        A comprehensive API for managing photobooth events, QR code payments, and real-time communication.              ## Features       - 🎫 Event Management (CRUD operations)       - 💳 PayMongo Payment Integration         - 🔄 Dynamic QR Code Generation (30-min expiry)       - ⚡ Real-time WebSocket Updates       - 🔐 Supabase Authentication       - 📊 Payment Analytics              ## Authentication       Most endpoints require a Bearer token from Supabase authentication.       Add your token to the \"Authorize\" button above to test endpoints.              ## Real-time Updates              **Client-side Polling:** Clients poll QR code status endpoints for real-time updates.              **QR Code Status Endpoint:** `GET /api/qr-codes/{qrCodeId}/status`              **Polling Strategy:** Clients should poll every 2-3 seconds to check for status changes.     
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@easypicsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

